### ISSUE TITLE
sass vite generating empty import paths

### ISSUE THREAD

**Issue by lars-zweifel** [mmssolutionsio/simple-reporting-library#11]
Currently when running `npm run dev` the css generation fails in `.nswow/app.scss`.

## Expected Behavior
Generate all imports for each component

## Context (Environment)
Windows 11
Powershell 7 x64
Node v22.6.0 | npm 10.8.2

## Detailed Description
```
10:30:59 [vite] Internal server error: [sass] Can't find stylesheet to import.
  ╷
2 │ @import "";
  │         ^^
  ╵
  .nswow\app.scss 2:9  root stylesheet
  Plugin: vite:css
  File: D:\nhs\test-reportinglibrary\TESTDesugn01\.nswow\app.scss:2:9
  Error: Can't find stylesheet to import.
    ╷
  2 │ @import "";
    │         ^^
    ╵
    .nswow\app.scss 2:9  root stylesheet
      at Object.wrapException (D:\nhs\test-reportinglibrary\TESTDesugn01\node_modules\sass\sass.dart.js:2301:43)
      at D:\nhs\test-reportinglibrary\TESTDesugn01\node_modules\sass\sass.dart.js:87075:25
      at _wrapJsFunctionForAsync_closure.$protected (D:\nhs\test-reportinglibrary\TESTDesugn01\node_modules\sass\sass.dart.js:5011:15)
      at _wrapJsFunctionForAsync_closure.call$2 (D:\nhs\test-reportinglibrary\TESTDesugn01\node_modules\sass\sass.dart.js:37820:12)
      at _awaitOnObject_closure.call$1 (D:\nhs\test-reportinglibrary\TESTDesugn01\node_modules\sass\sass.dart.js:37808:32)
      at Object._rootRunUnary (D:\nhs\test-reportinglibrary\TESTDesugn01\node_modules\sass\sass.dart.js:5414:18)
      at StaticClosure.<anonymous> (D:\nhs\test-reportinglibrary\TESTDesugn01\node_modules\sass\sass.dart.js:123112:16)
      at _CustomZone.runUnary$2$2 (D:\nhs\test-reportinglibrary\TESTDesugn01\node_modules\sass\sass.dart.js:39269:39)
      at _Future__propagateToListeners_handleValueCallback.call$0 (D:\nhs\test-reportinglibrary\TESTDesugn01\node_modules\sass\sass.dart.js:38334:51)
      at Object._Future__propagateToListeners (D:\nhs\test-reportinglibrary\TESTDesugn01\node_modules\sass\sass.dart.js:5206:93)
10:30:59 [vite] Pre-transform error: [sass] Can't find stylesheet to import.
  ╷
2 │ @import "";
  │         ^^
  ╵
```

**Comment by lars-zweifel** [comment]
This Issue might be related to #10 or path generation with mixed Windows backslashes and forwardslashes

**Comment by mikedoerer** [comment]
OK, schaue ich mir an. Powershell war hier nie im Einsatz.

**Comment by lars-zweifel** [comment]
The error starts in `@multivisio/nswow/scripts/build.js` where `process.cwd()` returns backslashes. 
I would propose to use `const CWD = path.normalize(process.cwd())` and use `CWD` everywhere instead of `resolve(process.cwd(), '...')`.

**Comment by mikedoerer** [comment]
Die Verwendung von path.resolve wurde in der 1. Version durch path.join ersetzt.
Glaube nicht das wir es in der 0. Version noch überarbeiten müssen.
Bitte aber noch mal testen. Habe es selbst noch nicht auf Windows getestet.
